# Define our Go application (which will act as our Authenticator/Switch)
client go-authenticator {
    ipaddr = 0.0.0.0/0      # In a real environment, restrict this to the switch's exact IP!
    secret = "GoRadiusSecret123" # The password the switch uses to talk to the server
    shortname = golab
}