config setup
    charondebug="ike 2, knl 2, cfg 2, net 2, esp 2, dmn 2, mgr 2"
    strictcrlpolicy=no

conn %default
    ikelifetime=60m
    keylife=20m
    rekeymargin=3m
    keyingtries=1
    keyexchange=ikev2 # We are explicitly forcing the modern IKEv2 protocol
    authby=secret     # This tells strongSwan to use a Pre-Shared Key (PSK)

conn site-to-site
    left=10.0.0.10             # Alice's IP
    leftsubnet=10.0.0.10/32    # The network behind Alice (just herself in this case)
    leftid=alice@lab.local     # Alice's logical identifier
    right=10.0.0.20            # Bob's IP
    rightsubnet=10.0.0.20/32   # The network behind Bob
    rightid=bob@lab.local      # Bob's logical identifier
    auto=start                 # Alice will actively try to initiate the tunnel on boot
    type=tunnel                # Explicitly defining IPsec Tunnel Mode