config setup
    charondebug="ike 2, knl 2, cfg 2, net 2, esp 2, dmn 2, mgr 2"
    strictcrlpolicy=no

conn %default
    ikelifetime=60m
    keylife=20m
    rekeymargin=3m
    keyingtries=1
    keyexchange=ikev2
    authby=secret

conn site-to-site
    left=10.0.0.20             # Bob's IP (From Bob's perspective, he is 'left')
    leftsubnet=10.0.0.20/32
    leftid=bob@lab.local
    right=10.0.0.10            # Alice's IP
    rightsubnet=10.0.0.10/32
    rightid=alice@lab.local
    auto=add                   # Bob will passively listen and wait for Alice to initiate
    type=tunnel